from selenium.webdriver.common.by import By

class OrderPageLocators:
    NAME_FIELD = (By.XPATH, "(.//input[contains(@class, 'Input')])[2]")
    SURNAME_FIELD = (By.XPATH, "(.//input[contains(@class, 'Input')])[3]")
    ADDRESS_FIELD = (By.XPATH, "(.//input[contains(@class, 'Input')])[4]")
    STATION_DROPDOWN_LIST_BUTTON = (By.CSS_SELECTOR, ".select-search__input")
    STATION_DROPDOWN_LIST_ITEMS = (By.CSS_SELECTOR, ".select-search__row")
    PHONE_NUMBER_FIELD = (By.XPATH, "(.//input[contains(@class, 'Input')])[5]")
    NEXT_BUTTON = (By.CSS_SELECTOR, "div[class^='Order_NextButton'] button")
    DATE_FIELD = (By.CSS_SELECTOR, ".react-datepicker__input-container input")
    ORDER_HEADER = (By.CSS_SELECTOR, "div[class^='Order_Header']")
    RENTAL_PERIOD_DROPDOWN_LIST_BUTTON = (By.CLASS_NAME, "Dropdown-root")
    RENTAL_PERIOD_DROPDOWN_LIST_ITEMS = (By.CLASS_NAME, "Dropdown-option")
    COLOR_CHECKBOX = (By.ID, "black")
    COMMENT_INPUT = (By.XPATH, "(.//input[contains(@class, 'Input')])[5]")
    CREATE_ORDER_BUTTON = (By.XPATH, ".//div[contains(@class, 'Order_Buttons')]/button[text()='Заказать']")
    CONFIRM_ORDER_BUTTON = (By.XPATH, ".//div[contains(@class, 'Order_Buttons')]/button[text()='Да']")
    SUCCESS_MODAL = (By.CSS_SELECTOR, "div[class^='Order_Modal']")
    MODAL_MESSAGE = (By.CSS_SELECTOR, "div[class^='Order_ModalHeader']")
    CHECK_STATUS_BUTTON = (By.CSS_SELECTOR, "div[class^='Order_NextButton'] button")